### ISSUE TITLE
Needs maintainers?

### ISSUE THREAD

**Issue by shinnn** [kombucha/gulp-assets#8]
@kombucha 

Currently this repo has some unreviewed PRs and an open issue, but haven't been updated since almost a year ago.

I'd happily maintain this repo if you want to collaborate me :)

**Comment by kombucha** [comment]
Sorry if I haven't been on top of things ^^'.
I'm grateful for your offer and contributions, I just never can find the time or will.

**Comment by shinnn** [comment]
Thanks.

So, would you mind adding me as a collaborator to this repository?
https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by kombucha** [comment]
Sure, here you go !

**Comment by shinnn** [comment]
Great :+1: 

And, could you give me write access for npm package? (`npm author add shinnn` in the right directory should do the trick)

**Comment by kombucha** [comment]
Don't know if you got a notification, but it's done !

**Comment by shinnn** [comment]
Now I have write access. Thanks! :100:
